/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ryota' at '16/02/03 23:17' with Gradle 2.10
 *
 * @author ryota, @date 16/02/03 23:17
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
