/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'ryota' at '16/02/03 23:17' with Gradle 2.10
 *
 * @author ryota, @date 16/02/03 23:17
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
